apiVersion: v1
kind: ConfigMap
metadata:
  name: autospec-config
  namespace: semute
data:
  APP_NAME: AutoSpec
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: https://semute.hackathon.sev-2.com
  LOG_CHANNEL: stderr
  LOG_LEVEL: info
  DB_CONNECTION: pgsql
  DB_HOST: 103.185.52.138
  DB_PORT: "1185"
  DB_DATABASE: semute
  SESSION_DRIVER: file
  CACHE_STORE: file
  QUEUE_CONNECTION: database
  FILESYSTEM_DISK: local
