apiVersion: v1
kind: Secret
metadata:
  name: autospec-secret
  namespace: semute
type: Opaque
stringData:
  APP_KEY: base64:cXbTlQaueqUZTfZOxFyxY3L8Z0/6CFDk5wPuDKmH51s=
  DB_USERNAME: replace-with-db-username
  DB_PASSWORD: replace-with-db-password
  LLM_API_KEY: replace-with-llm-api-key
  GOOGLE_CLIENT_ID: replace-with-google-client-id
  GOOGLE_CLIENT_SECRET: replace-with-google-client-secret
